# Generated by Django 4.2 on 2026-01-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('cancelled', 'Cancelado'), ('done', 'Hecho'), ('paid', 'Pagado')], default='draft', max_length=11)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.client')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.saleorder')),
            ],
        ),
    ]
