# Generated by Django 4.2 on 2026-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_saleorder_saleorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='direccion',
            field=models.TextField(null=True),
        ),
    ]
