# Generated by Django 4.2 on 2026-01-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_client_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
